Обновление код-стайла
surfstudio/SwiftCodestyle pull request #3
Opened 2019-02-25 09:48 UTC by ismetanin

## Что сделано
Взят вот [этот](https://github.com/airbnb/swift) код стайл и переписан на русский язык с учетом некоторых правил, которые используются у нас в студии.

## Что нужно будет ещё сделать
- Дописать раздел про разграничение кода MARK-ами;
- Возможно добавить новых правил SwiftLint и описать некоторые существующие;
- Исправить недочеты по описанию (орфография, пунктуация и т.п).

## На что обратить внимание
Описанные правила **не совпадают и не могут совпадать со стилем написания кода всех людей в студии**. 
Если вам **важно** отстоять какие-то полюбившиеся правила форматирования кода, то нужно это делать здесь и сейчас. Вот [ссылка](https://github.com/surfstudio/SwiftCodestyle/blob/f726d9081e6e3459c75957ba83d74b567b4cb705/README.md) чтобы открыть код стайл в новом формате, а не читать его через diff.

SwiftFormat мы не используем, но думаю пора начать.

2019-02-25 12:22 UTC, pavbox commented on README.md
> +* <a id='column-width'></a>(<a href='#column-width'>link</a>) **Каждая строка должна иметь максимальную длину в 120 символов.** [![SwiftLint: line_length](https://img.shields.io/badge/SwiftLint-line_
а нам точно нужны эти линки ? выглядит стремно :( ну и спойлеры тоже. Может не громоздкое `(link)` писать, а `#`? Вроде все понимают, что означает якорь 🤓

2019-02-25 12:22 UTC, pavbox commented on resources/swiftlint.yml
> +        regex: "@IBOutlet weak var"
Может лучше сделать `@IBOutlet ?(weak){0,1} var`? тогда будет ловить и для групповых Outlets ([UIView]!).

2019-02-25 14:07 UTC, ismetanin commented on README.md
> +* <a id='column-width'></a>(<a href='#column-width'>link</a>) **Каждая строка должна иметь максимальную длину в 120 символов.** [![SwiftLint: line_length](https://img.shields.io/badge/SwiftLint-line_
Линки думаю могут пригодится, в том же ПР-е пошарить, например. Но вот `#` выглядит лучше `(link)`, согласен
По мне спойлеры выглядят нормально и позволяют сэкономить кучу места

2019-02-25 18:57 UTC, pavbox commented on README.md
> +## Table of Contents
Можно написать "Содержание", чтобы пункт не сильно отличался от остальных.

2019-02-25 18:57 UTC, pavbox commented on README.md
> +    static let worldName: String = "Earth"
Этот литерал неявно приводится к строке или может стать substring каким-либо? а то у нас есть раздел про это, а в этой строке будто сами же нарушаем ✌️

2019-02-25 18:57 UTC, pavbox commented on README.md
> +      isFamilyFriendly = !allowsPets
если честно, не очень эстетично выглядит, когда половина свойств self, а другая – без self. Но может придераюсь как ты в описании сказал :) что парни скажут

2019-02-25 18:57 UTC, pavbox commented on README.md
> +* <a id='prefer-immutable-values'></a><a href='#prefer-immutable-values'>#</a> **Используйте неизменяемые значения где это возможно.** Используйте `map` и `compactMap` вместо добавления в новую колле
вместо* небольшая опечатка

2019-02-25 18:57 UTC, pavbox commented on README.md
> +      API.request() { [weak self] response in
а будем использовать trailing closures?

2019-02-25 18:57 UTC, pavbox commented on README.md
> +  Проще рассуждать о блоке кода, когда все операторы `guard` сгруппированы вверху, а не смешаны с бизнес-логикой.
тут, кстати, интересный кейс может быть, что некоторые guards только после выполнения какого-либо кода могут быть получены. Например:

```swift

func request(url: URL?, login: String?, password: String?) {
    guard let url = url, let login = login, let password = password else {
        // throw error
        return
    }

    requestCount -= 1

    guard let encrpyptedKey = getEncryptedKey(for: login, by: password) else {
        // another error
        return
    }

    send(url: url, key: encrpyptedKey)
}
```

Придумывал как мог :D но тут мб все можно на ошибку логики списать. Если каждая функция отвечает за свой кусок алгоритма, то мб такого не произойдет. Но, надеюсь, идею передал

2019-02-25 19:20 UTC, pavbox commented
В целом даже норм выглядит. Когда читал старый код стайл, хотел много добавить, но тут вроде все горячие точки закрываются.

Добавил бы:
- trailing closures
- golden paths (именно описание зачем и отличие if-else)
- добавить правило описывать каждый модуль в configurator несколькими предложениями
- подписывать поля документирующим комментом, если назначение неочевидно
- как вариант еще в отдельный док – практики с extensions (когда выносить, когда нет)
- из [API Guidelines](https://swift.org/documentation/api-design-guidelines/) добавил бы пункт про **Prefer method and function names that make use sites form grammatical English phrases.** Мне кажется, это довольно сильно улучшает читаемость и понятность.
- кажется важным описать комментирование сложных элементов. Хотя это вроде всем понятно, но код стайл как раз и описывает такие понятные темы, чтобы не было вопросов. Комменты документирующие параметры, назначение функции, и что возвращает.

- еще у меня есть такая идея-фикс (сомнительная :D), чтобы добавлять для больших структур свойства, возвращающие объекты с дефолтными параметрами. `SomeObject.default` тоже самое, что `SomeObject(prop1: .normal, prop2: "", prop3: 0, prop4: nil)`. Правда, пока писал, потерял полезность такого ) в общем, что-то вроде factory паттерна.

Думаю, чтобы тебе все это не добавлять, можно просто в Issues покидать, что покажется полезным.

2019-02-25 19:25 UTC, LastSprint commented
> * еще у меня есть такая идея-фикс
Конструктор по-умолчанию на что?

2019-02-25 19:33 UTC, pavbox commented
> > * еще у меня есть такая идея-фикс
> Конструктор по-умолчанию на что?
Ну говорю сомнительная ) Множественные конструкторы как-то именовать разве что `AnyDefaultEntity.payment`, `AnyDefaultEntity.blessedPayment` (типа обогащенная доп. параметрами).
@LastSprint

2019-02-25 20:11 UTC, LastSprint commented on README.md
> +      isFamilyFriendly = !allowsPets
У self есть замечательное свойство - позволяет глазами разбирать скоупы существования переменных. Эстетика тут не при чем. Банально не удобно.

2019-02-25 20:11 UTC, LastSprint commented on README.md
> +      API.request() { [weak self] response in
см. выше

2019-02-25 20:11 UTC, LastSprint commented on README.md
> +  //  Copyright © 2018 Airbnb. All rights reserved.
А выше исправил на Surf)

2019-02-26 04:37 UTC, drxlx commented on README.md
> +* <a id='alphabetize-imports'></a><a href='#alphabetize-imports'>#</a> **Сортируйте импорты по алфавиту и ставьте их после комментариев в заголовке файла.** [![SwiftFormat: sortedImports](https://img
Может добавить, что можно не писать import Foundation, если либа итак уже делает import Foundation. Это позволит сократить количество импортов.

2019-02-26 04:39 UTC, drxlx commented on README.md
> +* <a id='time-intensive-init'></a><a href='#time-intensive-init'>#</a> **Избегайте выполнение любой значимой или времязратной работый в `init()`.** Избегайте таких действий, как открытие соединения с
Очепятка `времязратной`

2019-02-26 06:18 UTC, ismetanin commented on README.md
> +      isFamilyFriendly = !allowsPets
Тут пример ещё синтетический на самом деле, редко где-то в init встречаешь такой код

2019-02-26 06:26 UTC, ismetanin commented on README.md
> +  Проще рассуждать о блоке кода, когда все операторы `guard` сгруппированы вверху, а не смешаны с бизнес-логикой.
Код стайл диктует набор правил, которых следует придерживаться по мере возможности. То есть если нельзя выполнить их все в начале, то это тоже ок

2019-02-26 06:38 UTC, ismetanin commented on README.md
> +  //  Copyright © 2018 Airbnb. All rights reserved.
И тут тоже исправлю :)

2019-02-26 06:41 UTC, ismetanin commented
@pavbox 

> golden paths (именно описание зачем и отличие if-else)

Отличие if-else? Не понял

> добавить правило описывать каждый модуль в configurator несколькими предложениями

Если ты говоришь про Surf MVP, то этот стайл не про Surf MVP, а про написание кода на языке Swift. То есть добавить можно, но не сюда

> Множественные конструкторы как-то именовать разве что `AnyDefaultEntity.payment`, `AnyDefaultEntity.blessedPayment` (типа обогащенная доп. параметрами).

Что это нам даст? Получается у тебя и конструктора не будет с точки зрения синтаксиса, что осложнит использование свойств, которые ты должен задать на этапе инициализации

> подписывать поля документирующим комментом, если назначение неочевидно

Мне кажется проще не давать неочевидных названий. А если мы это напишем, то укажем на возможность давать плохие названия переменным

> * из [API Guidelines](https://swift.org/documentation/api-design-guidelines/) добавил бы пункт про **Prefer method and function names that make use sites form grammatical English phrases.** Мне кажется, это довольно сильно улучшает читаемость и понятность.

Я же указал что _"Этот гайд являеся дополнением официальному [Swift API Design Guidelines](https://swift.org/documentation/api-design-guidelines/)"_ , то есть подразумевается что и с ним нужно ознакомиться

2019-02-26 06:43 UTC, ismetanin commented on README.md
> +      API.request() { [weak self] response in
[Вот сюда](https://github.com/surfstudio/SwiftCodestyle/blob/2d23d907fa241d61763f04f8193ecafeed93d1da/README.md#unnecessary-parens)

2019-02-26 06:56 UTC, pavbox approved these changes

2019-02-26 19:30 UTC, chausovSurfStudio commented on README.md
> +      isFamilyFriendly = !allowsPets
плюсую, на святое покушаетесь, даешь self в конструкторах

2019-02-27 06:45 UTC, ismetanin commented on README.md
> +      isFamilyFriendly = !allowsPets
В конструкторах в целом согласен, чтобы было консистентно можно юзать

2019-02-27 07:07 UTC, ismetanin commented on README.md
> +      isFamilyFriendly = !allowsPets
Добавил в SwiftFormat исключение init-only и дописал, что правило не распространяется на инициализаторы

2019-02-28 10:07 UTC, drxlx approved these changes

2019-02-28 10:09 UTC, LastSprint commented on README.md
> +      isFamilyFriendly = !allowsPets
Да дело ж не в инитах даже. Любой код внутри объекта проще читать при наличии self.

2019-02-28 13:06 UTC, ismetanin commented on README.md
> +      isFamilyFriendly = !allowsPets
Чисто на мой вкус - проще читать без self
Подсветка помогает отделить скоуп существования переменных

2019-03-01 11:14 UTC, s4x commented on README.md
> +  // Неправильно
Очень удобно, если нужно добавить еще 1 значение, когда запятушка уже есть ☺️

2019-03-01 11:17 UTC, LastSprint commented on README.md
> +      isFamilyFriendly = !allowsPets
Ну кодстайл это не про вкусовщину

2019-03-01 11:18 UTC, LastSprint commented on README.md
> +  // Неправильно
В Go кстати на уровне синтаксиса необходимо ставить запятую. 
То есть если ее не поставить, то программа не скомпилируется.

2019-03-01 11:44 UTC, ismetanin commented on README.md
> +      isFamilyFriendly = !allowsPets
Не про вкусовщину, но ты же не можешь измерить простоту чтения кода?

2019-03-01 12:12 UTC, LastSprint commented on README.md
> +      isFamilyFriendly = !allowsPets
Ну вообще-то могу) 
Вполне объективно, что для определения скупа разумно использовать языковые средства, а не средства редактора

2019-03-01 12:13 UTC, LastSprint commented on README.md
> +      isFamilyFriendly = !allowsPets
Я вообще считаю, что это не стоит выносить на уровень кодстайла.

2019-03-01 14:17 UTC, gregoryvit commented on README.md
> +      isFamilyFriendly = !allowsPets
Тут после "пока это не нужно для уточнения" и "пока того не требует язык" можно закрывать тред :)

Когда появляются такие конструкции, то начинает увеличиваться ментальная нагрузка. **Поэтому условия типа "в конструкторах делаем, а в других местах нет" давайте не вводить.** Лучше если будет однообразие.

Про сам `self` тоже вроде как-то обсуждали момент этот и сошлись на том, что явное лучше неявного → лучше везде писать self.
Не уверен, что нужно это фиксировать на уровне студии, но на уровне проекта **необходимо**.

2019-03-01 14:20 UTC, gregoryvit commented on README.md
> +      isFamilyFriendly = !allowsPets
> Не про вкусовщину, но ты же не можешь измерить простоту чтения кода?

Можно. Чем меньше неоднозначности и вопросов возникает, тем проще читать.

2019-03-01 14:20 UTC, ismetanin commented on README.md
> +      isFamilyFriendly = !allowsPets
На самом деле SwiftFormat даже имеет специальную конфигурацию на скип проверки в init-ах
Моё мнение что это нужно оставить, а выпилить правило уже можно в проекте

2019-03-03 15:46 UTC, chausovSurfStudio requested changes
Отдельно еще отмечу, что наверняка что-то упустим или бахнем лишнего, в первое время надо будет обкатывать вдумчиво на проектах

2019-03-03 15:46 UTC, chausovSurfStudio commented on README.md
> +* <a id='use-implicit-types'></a><a href='#use-implicit-types'>#</a> **Не указываете типы там, где они легко могут быть выведены**
Вот тут надо очень аккуратным быть) есть места, где правило действительно нужно, а есть места, где ну ни к чему слепое следование правилам. Как пример: Миша после работы со мной вернулся на предыдущий свой проект и стал там это правило применять, вплоть до того, что UIFont ему не понравился, давайте не будем его писать.
Ну то есть к примеру претензий нет, действительно все правильно, но UIFont как не указать, это ж святое( тут даже глазами натыкаешься на UIFont - и такой "да что мне дальше смотреть, и так понятно, шрифт какой-то", а то придется читать...
То есть я к тому, что вангую проблемы при внедрении правила на деле - много холивара будет, надо или нет не указывать тип. Для кого-то он будет "легко" выводим, а для кого-то - нет

2019-03-03 15:46 UTC, chausovSurfStudio commented on README.md
> +* <a id='omit-self'></a><a href='#omit-self'>#</a> **Не используйте `self` пока это не нужно для уточнения или пока того не требует язык.** Это правило не касается инициализаторов, там нужно использо
Отдельно упомяну еще раз - штука спорная. С одной стороны - мне не нравилось это свойство swift после перехода с obj-c, где self нужен по-любому, но ничего, привык со временем. Но тут если не прийти к общему соглашению - то кто-то будет его писать, кто-то нет, в итоге кодовая база будет разношерстной.

2019-03-03 15:46 UTC, chausovSurfStudio commented on README.md
> +* <a id='omit-function-void-return'></a><a href='#omit-function-void-return'>#</a> **Опускайте возвращаемы тип `Void`.** [![SwiftLint: redundant_void_return](https://img.shields.io/badge/SwiftLint-re
возвращаемыЙ, опечаточка)

2019-03-03 15:46 UTC, chausovSurfStudio commented on README.md
> +  guard true else {
хотелось бы увидеть в код-стайле соглашение насчет многострочных guard/if (когда в них проверяется более чем одно условие), как в таких случаях с отступами/переносами быть?

2019-03-03 15:46 UTC, chausovSurfStudio commented on README.md
> +### Функции
отдельно в это место коммент напишу: есть/будет ли какое-нибудь соглашение, когда надо использовать func, а когда вычисляемый var? То есть я человек, который может иногда определить func isEnabled() -> Bool, но можно ли так или это совсем неправильно и надо только var isEnabled: Bool { return ... }

2019-03-03 15:46 UTC, chausovSurfStudio commented on README.md
> +  Если класс должен быть переопределен, автор должен указать эту функциональность, опуская ключевое слово `final`.
от женщины с Uber слышал, что final также позволяют на несколько процентов вес сборки сократить :)
а тут еще и про пользу для performance нашел https://developer.apple.com/swift/blog/?id=27
кстати будет где-нибудь в код-стайле правила типа "IBOutlets делать private" ну или что-то в этом духе, не только про атулеты? или все же это к код-стайлу не относится?)

2019-03-03 15:46 UTC, chausovSurfStudio commented on README.md
> +  import UIKit
а не затеряются ли в таком случае UIKit/Foundation, которые как-бы неинтересны на самом деле, среди других важных вещей?

2019-03-03 15:46 UTC, chausovSurfStudio commented on README.md
> +* <a id='alphabetize-imports'></a><a href='#alphabetize-imports'>#</a> **Сортируйте импорты по алфавиту и ставьте их после комментариев в заголовке файла.** Если одна из библиотек уже импортирует как
го в код-стайл еще правило о том, что файлы/папки в проекте надо по алфавиту расставлять?) за исключением некоторых отдельных вещей, типа View/Presenter, где уже привычное расположение файлов регулируется генерамбой и здравым смыслом

2019-03-03 16:39 UTC, ismetanin commented on README.md
> +* <a id='use-implicit-types'></a><a href='#use-implicit-types'>#</a> **Не указываете типы там, где они легко могут быть выведены**
Тут скорее подразумевается вывод типов компилятором. То есть если тебе не надо указать явно, что это, например, не Double, а CGFloat, то и не нужно указывать тип

Но я соглашусь, что в целом почти каждое правило может быть оспоренно любым, кто привык к чему-то другому. Наша задача описать сейчас какие-то глобальные правила в целом к которым нужно стремиться всем. И понятно, что сначала будут проблемы с принятием этих правил

2019-03-03 16:41 UTC, ismetanin commented on README.md
> +  guard true else {
Я думал добавить раздел про отступы и переносы позже. У меня есть заготовка под это, но если мы и насчет них сейчас начнем спорить, то этот ПР никогда не смержится

2019-03-03 16:42 UTC, ismetanin commented on README.md
> +### Функции
Можешь закинуть это предложение в issue я думаю. Мне кажется хорошей идей описать это

2019-03-03 16:43 UTC, ismetanin commented on README.md
> +  Если класс должен быть переопределен, автор должен указать эту функциональность, опуская ключевое слово `final`.
Это скорее базовые принципы ООП, но тоже вместе с вычисляемыми свойствами в раздел можно будет положить

2019-03-03 16:46 UTC, ismetanin commented on README.md
> +* <a id='alphabetize-imports'></a><a href='#alphabetize-imports'>#</a> **Сортируйте импорты по алфавиту и ставьте их после комментариев в заголовке файла.** Если одна из библиотек уже импортирует как
Если напишешь к этому правилу тулзу, которая будет это сама делать каждый билд, например, или перед пушем, то будет круто :)

2019-03-03 16:47 UTC, ismetanin commented on README.md
> +* <a id='alphabetize-imports'></a><a href='#alphabetize-imports'>#</a> **Сортируйте импорты по алфавиту и ставьте их после комментариев в заголовке файла.** Если одна из библиотек уже импортирует как
Я даже видел где-то утилиту, которая так умеет

2019-03-03 16:48 UTC, ismetanin commented on README.md
> +  import UIKit
Думаю это будет не критично для чтения кода

2019-03-03 16:55 UTC, pavbox commented on README.md
> +* <a id='omit-self'></a><a href='#omit-self'>#</a> **Не используйте `self` пока это не нужно для уточнения или пока того не требует язык.** Это правило не касается инициализаторов, там нужно использо
думаю, любые нюансы на уровне проекта надо решать. Код-стайл так или иначе везде отличается мелочами. Главное – уметь говорить об этом на старте и на ревью! )

2019-03-03 16:59 UTC, pavbox commented on README.md
> +* <a id='alphabetize-imports'></a><a href='#alphabetize-imports'>#</a> **Сортируйте импорты по алфавиту и ставьте их после комментариев в заголовке файла.** Если одна из библиотек уже импортирует как
надо либо это обсудить тогда, либо закинуть в "идеи". В таком виде предложение просто забудется :(

2019-03-03 17:01 UTC, pavbox commented
Ребят, давайте смержим его уже %) Ваня проделал большую работу! Прочие штуки добавим в Issues и будем уже всеми фиксить, а не Ваню напрягать ⚡️ 
@LastSprint @chausovSurfStudio

2019-03-04 06:17 UTC, chausovSurfStudio commented on README.md
> +* <a id='alphabetize-imports'></a><a href='#alphabetize-imports'>#</a> **Сортируйте импорты по алфавиту и ставьте их после комментариев в заголовке файла.** Если одна из библиотек уже импортирует как
synx или как-то так оно называется, но она прям все под одну гребенку расставляет, меня это напрягает (ну то есть я, к примеру, привык, что в папке View у меня сначала viewController, потом xib, потом viewInput/output, она же по алфавиту их расставит)
Но наличие утилиты, на мой взгляд, не столь критично, как наличие правила - на алфавитный порядок импортов правил/тулзы какой-либо тоже нет же

2019-03-04 06:19 UTC, chausovSurfStudio commented
Не, ну можно и смержить, работа большая, тут без вопросов) просто не вижу смысла торопиться - это не таск, который надо быстрее закончить и показать продукт заказчику, а после мержа этого ПРа мы не станем внезапно все красиво и единообразно писать.
Да и недообсужденный код-стайл при применении на практике потом только больше вопросов вызовет

2019-03-04 06:31 UTC, ismetanin commented on README.md
> +* <a id='alphabetize-imports'></a><a href='#alphabetize-imports'>#</a> **Сортируйте импорты по алфавиту и ставьте их после комментариев в заголовке файла.** Если одна из библиотек уже импортирует как
synx я использую в темплейтах проектов, его можно научить не исправлять в нужных папках
Но он там ещё баговал на больших проектах у меня как-то, надо будет протестировать
Добавил в #4

2019-03-04 06:34 UTC, LastSprint commented on README.md
> +      isFamilyFriendly = !allowsPets
Может немного реорганзивать структуру?
Сделать набор базовых правил и набор дополнительных
Тогда на конкретном проекте ты будешь не удалять правила, а добавлять их. 
Ну и скелет кода всегда выглядит одинаково и всегда одинаково читается, за исключением мелочей вроде этой.

2019-03-04 06:36 UTC, ismetanin commented on README.md
> +  guard true else {
Добавил пока в issue. #5

2019-03-04 06:38 UTC, ismetanin commented on README.md
> +### Функции
Добавил в #6

2019-03-04 06:40 UTC, ismetanin commented on README.md
> +  Если класс должен быть переопределен, автор должен указать эту функциональность, опуская ключевое слово `final`.
На самом деле это правило то уже есть:
https://github.com/surfstudio/SwiftCodestyle/blob/a57154d8bac007476fc35135dcda980b5cfaeb94/README.md#limit-access-control
Возможно стоит пример написать

2019-03-04 06:45 UTC, ismetanin commented on README.md
> +  Если класс должен быть переопределен, автор должен указать эту функциональность, опуская ключевое слово `final`.
[Написал](
https://github.com/surfstudio/SwiftCodestyle/blob/f5e6e5785b6858e124a8297312ad2f2d004f011e/README.md#limit-access-control)

2019-03-04 07:16 UTC, ismetanin commented on README.md
> +      isFamilyFriendly = !allowsPets
@LastSprint 
Как ты видишь реорганизованную структуру?

2019-03-04 07:44 UTC, ismetanin commented on README.md
> +      isFamilyFriendly = !allowsPets
@LastSprint @gregoryvit @chausovSurfStudio
Вот смотрите почему мне не нравится использовать `self` всегда:
Имеем вот такую функцию
```swift
private func configureSubviews() {
    view.addSubview(rootContainer)
    rootContainer.addSubview(segmentedMenuView)
    rootContainer.addSubview(pageViewContainer)
    addChild(pageViewController)
    pageViewContainer.addSubview(pageViewController.view)
}
```
Если написать всё по правилу "Используй self всегда" получится вот так
```swift
private func configureSubviews() {
    self.view.addSubview(self.rootContainer)
    self.rootContainer.addSubview(self.segmentedMenuView)
    self.rootContainer.addSubview(self.pageViewContainer)
    self.addChild(self.pageViewController)
    self.pageViewContainer.addSubview(self.pageViewController.view)
}
```
На 5 строках кода разница в 50 символов + мысленно всё равно приходится скипать начало `self` каждой строки + в целом метод смотрится уже массивнее

Но, кажется, я в меньшинстве с такими предпочтениями 🤷‍♂️

2019-03-04 08:30 UTC, pavbox commented on README.md
> +      isFamilyFriendly = !allowsPets
По мне, тут правильно выглядит первый вариант. Мой поинт в том, что если в init писать self для одной части (для чего-то всегда придется писать) и не писать для другой, то и получится непонимание неймспейса, как Саша говорил. То есть различишь это только по подсветке xcode (что так себе работает) или придется смотреть все переменные выше в функции.

То есть речь о том, чтобы приводить все к self, если в этом неймспейсе уже есть некоторые поля, которые не могут без self – блоки и инициализацторы, например.

Что думаете?

2019-03-04 08:34 UTC, Virpik commented on README.md
> +      isFamilyFriendly = !allowsPets
Давайте напишем плагин, для xCode, который в зависимости от предпочтений, будет подставлять или убирать `self` =)

2019-03-04 13:55 UTC, gregoryvit commented on README.md
> +      isFamilyFriendly = !allowsPets
Вариант с основными правилами и вкусовщиной мне видится логичным. Организовать можно просто: в readme разбить на 2 раздела, а в конфигах комментариями отделить эти два набора правил + второстепенные закомментить.

2019-03-04 13:56 UTC, gregoryvit commented
Кроме вопроса с `self` у нас больше нет спорных моментов?)

2019-03-05 05:52 UTC, chausovSurfStudio approved these changes

2019-03-05 08:30 UTC, ismetanin commented
>Кроме вопроса с `self` у нас больше нет спорных моментов?)

@gregoryvit Я так понимаю - нет

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2019-03-11 20:20 UTC, gregoryvit commented
> > Кроме вопроса с `self` у нас больше нет спорных моментов?)
> 
> @gregoryvit Я так понимаю - нет
> 
> Sent with [GitHawk](http://githawk.com)

@ismetanin  Тогда давай делать раздел с необязательными правилами.

@surfstudio/ios-devs Что еще в этот раздел вынесем?

2019-03-12 07:22 UTC, ismetanin commented
@gregoryvit Я все же не понимаю как он должен выглядеть
Вот сейчас у нас такое содержание, каким оно должно стать после внесения правок?
```
## Содержание

- [Surf Swift Style Guide]
  - [Цели]
  - [Принципы]
  - [Содержание]
  - [Xcode форматирование]
  - [Именование]
  - [Стиль]
    - [Функции]
    - [Замыкания]
    - [Операторы]
  - [Паттерны]
  - [Организация файлов]
  - [Совместимость с Objective-C]
```

Мне кажется вот с двумя секциями мы только создадим ещё больше нагрузки на читателя

2019-04-10 15:42 UTC, gregoryvit commented
> @gregoryvit Я все же не понимаю как он должен выглядеть
> Вот сейчас у нас такое содержание, каким оно должно стать после внесения правок?
> 
> ```
> ## Содержание
> 
> - [Surf Swift Style Guide]
>   - [Цели]
>   - [Принципы]
>   - [Содержание]
>   - [Xcode форматирование]
>   - [Именование]
>   - [Стиль]
>     - [Функции]
>     - [Замыкания]
>     - [Операторы]
>   - [Паттерны]
>   - [Организация файлов]
>   - [Совместимость с Objective-C]
> ```
> Мне кажется вот с двумя секциями мы только создадим ещё больше нагрузки на читателя

Не вижу проблемы добавить сюда еще один пункт и все спорные правила туда убрать)

2019-04-10 15:46 UTC, ismetanin commented
> Не вижу проблемы добавить сюда еще один пункт и все спорные правила туда убрать)

@gregoryvit Мне кажется это лишней нагрузкой на читателя. Может всё таки отправить это в тех доки проектов? То есть если хочешь какое-то правило не использовать, то так и напиши в тех доке своего проекта. А читателю вот будет вообще не понятно: "Правила опциональные, но мне то их применять или нет?"

2019-04-10 15:56 UTC, gregoryvit commented
> Может всё таки отправить это в тех доки проектов?
В тех доке все опциональные правила обязательно должны быть описаны.

> То есть если хочешь какое-то правило не использовать, то так и напиши в тех доке своего проекта.
Не, давай сделаем так, чтобы явно были выделены правила, которые действуют всегда, а есть правила, которые описываются в тех доке. Отмена каких-то правил скорее исключением должна быть, а не нормальной практикой.
Если кажется, что введение отдельной секции как-то усложнит док, то просто убираем правило тогда. 

> А читателю вот будет вообще не понятно: "Правила опциональные, но мне то их применять или нет?"
Как раз наоборот же :)
Если правило опциональное, то ответ нужно в тех доке проекта искать. Если не опциональное, то действует.  
Стоит после этого раздела абзац написать с описанием того, что это за раздел, если есть опасение, что читатель не поймет.

2019-04-10 16:05 UTC, ismetanin commented
> Отмена каких-то правил скорее исключением должна быть, а не нормальной практикой.

Проблема в том что у нас возникло **одно спорное правило** - строгое использование self. И я даже провел маленький ресёрч, единственный человек которого я нашел среди нас и который ему стабильно следует - это @LastSprint

Вот если мы ещё наберем правил на такой раздел, я не против, но писать такое ради одного правила, которое как раз таки действительно редкое исключение мне кажется не очень разумной затеей.

2019-04-10 16:08 UTC, merged