IDPT-401 *-able misuse in protocol names
surfstudio/SwiftCodestyle pull request #8
Opened 2020-06-17 16:22 UTC by DanilKomarov

# Что сделано
- Добавлена рекомендация по именованию протоколов для более точного обозначения функционального значения этих протоколов.

2020-07-06 04:45 UTC, LastSprint approved these changes

2020-07-06 07:39 UTC, Alelenka approved these changes

2020-07-18 11:34 UTC, chausovSurfStudio approved these changes

2020-07-19 13:51 UTC, erorrov requested changes

2020-07-19 13:51 UTC, erorrov commented on README.md
> +* <a id='able-suffix-misuse'></a><a href='#able-suffix-misuse'>#</a> **Названия протоколов должны явно отражать функциональное значение протоколов**. Если протокол описывает методы, реализующие дейст
```suggestion
* <a id='able-suffix-misuse'></a><a href='#able-suffix-misuse'>#</a> **Названия протоколов должны явно отражать функциональное значение протоколов**. Если протокол описывает методы, реализующие действия самого объекта над другими объектами, лучше использовать Noun; если же он описывает действия, которые можно совершить над объектом, реализующим протокол, лучше использовать Adjective с суффиксом -able.
```

2020-07-19 13:53 UTC, DanilKomarov commented on README.md
> +* <a id='able-suffix-misuse'></a><a href='#able-suffix-misuse'>#</a> **Названия протоколов должны явно отражать функциональное значение протоколов**. Если протокол описывает методы, реализующие дейст
Спасибо! Очепятка при копировании.

2020-07-19 13:55 UTC, erorrov approved these changes

2020-09-27 21:30 UTC, merged